apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstnote
  labels:
    app: firstnote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstnote
  template:
    metadata:
      labels:
        app: firstnote
    spec:
      containers:
      - name: firstnote
        image: fbnquestdocker/firstnoteapi:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: fbnquest-registry-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firstnote-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: firstnote.fbnq-mspx-l01.fbnmerchantbank.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: firstnote-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: firstnote-service
spec:
  selector:
    app: firstnote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


